services:
  superset:
    build: ./superset_app
    image: superset_actualizado
    container_name: superset
    ports:
      - "8088:8088"
    env_file:
      - ./superset_app/superset.env
    volumes:
      - ./superset_app/app/superset_config.py:/app/pythonpath/superset_config.py
      - superset_home:/app/superset_home
    command: >
      /bin/sh -c "
        superset db upgrade &&
        superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@superset.com --password admin &&
        superset init &&
        superset run -h 0.0.0.0 -p 8088
      "


volumes:
  superset_home:
