volumes:
  middle_var: {}
  historical_var: {}
  broker_var: {}
  coordinator_var: {}
  router_var: {}
  druid_shared: {}

services:
  spark:
    image: docker.io/bitnami/spark:3.3
    container_name: spark
    env_file:
      - ./app_spark/spark.env
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./app_spark/:/opt/spark-app
      - ./app_spark/data:/app/data
    user: root
    command: >
      bash -c "spark-submit --master local[*] /opt/spark-app/etl_script.py"
    networks:
      - localnet


  postgres:
    image: postgres:17.5-alpine3.22
    container_name: postgres
    env_file: ./app_postgres/postgres.env
    volumes:
      - ./app_postgres/db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - localnet

  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.9
    ports:
      - "2181:2181"
    environment:
      - ZOO_MY_ID=1
    networks:
      - localnet

  coordinator:
    image: apache/druid:33.0.0
    user: root
    container_name: coordinator
    volumes:
      - ./app_druid/druid_shared:/opt/shared
      - ./app_druid/coordinator/coordinator_var:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres
    ports:
      - "8081:8081"
    command:
      - coordinator
    env_file:
      - ./app_druid/druid.env
    networks:
      - localnet

  broker:
    image: apache/druid:33.0.0
    user: root
    container_name: broker
    volumes:
      - ./app_druid/broker/broker_var:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "8082:8082"
    command:
      - broker
    env_file:
      - ./app_druid/druid.env
    networks:
      - localnet

  historical:
    image: apache/druid:33.0.0
    user: root
    container_name: historical
    volumes:
      - ./app_druid/druid_shared:/opt/shared
      - ./app_druid/historical/historical_var:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "8083:8083"
    command:
      - historical
    env_file:
      - ./app_druid/druid.env
    networks:
      - localnet

  middlemanager:
    image: apache/druid:33.0.0
    user: root
    container_name: middlemanager
    volumes:
      - ./app_druid/druid_shared:/opt/shared
      - ./app_druid/middlemanager/middle_var:/opt/druid/var
      - ./app_spark/output:/opt/data/parquet
    depends_on:
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "8091:8091"
      - "8100-8105:8100-8105"
    command:
      - middleManager
    env_file:
      - ./app_druid/druid.env
    networks:
      - localnet

  router:
    image: apache/druid:33.0.0
    user: root
    container_name: router
    volumes:
      - ./app_druid/router/router_var:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "8888:8888"
    command:
      - router
    env_file:
      - ./app_druid/druid.env
    networks:
      - localnet

networks:
  localnet:

