services:
  superset:
    build: /superset_app
    image: my_superset_with_pillow
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      SUPERSET_ENV: production
      SUPERSET_CONFIG_PATH: /app/pythonpath/superset_config.py
      SUPERSET_LOAD_EXAMPLES: "no"
      SUPERSET_USERNAME: admin
      SUPERSET_PASSWORD: admin
      SUPERSET_EMAIL: admin@superset.com
      SUPERSET_FIRSTNAME: Superset
      SUPERSET_LASTNAME: Admin
    volumes:
      - ./superset_app/app/superset_config.py:/app/pythonpath/superset_config.py
      - superset_home:/app/superset_home
    command: >
      /bin/sh -c "
        superset db upgrade &&
        superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@superset.com --password admin &&
        superset init &&
        superset run -h 0.0.0.0 -p 8088
      "


volumes:
  superset_home:
