FROM docker.io/bitnami/spark:3.3

# Switch to root user to create a new user
USER root

# Create a new user with UID 1000
#RUN useradd -u 1000 -m sparkuser

# Switch back to the new user
#USER sparkuser

# Set the working directory
#WORKDIR /app
